sudo: required
language: node_js

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - yarn

services:
  - docker

jobs:
  include:
    # - &build
    #   stage: Build
    #   script:
    #     - yarn lint
    #     - yarn build
    #   node_js: "10"

    # - &unit
    #   stage: Test
    #   script: yarn test:unit
    #   name: "NodeJS 10 unit tests"
    #   node_js: "10"

    # - &installer
    #   script: yarn installer:ci
    #   name: "NodeJS 10 installer test"
    #   if: branch IN (master, develop)
    #   node_js: "10"
    #   addons:
    #     chrome: stable

    - build_image:
      name: "Build docker image"
      stage: docker_build
      node_js: "10"
      script:
        - docker build -t registry.storefrontcloud.io/mkoszut-storefrontcloud-io/vue-storefront:$COMMIT -f dev/docker/Dockerfile .
        - echo $DOCKER_PASSWORD | docker login  -u="$DOCKER_USERNAME" --password-stdin registry.storefrontcloud.io
        - docker push registry.storefrontcloud.io/mkoszut-storefrontcloud-io/vue-storefront:$COMMIT

    - deploy_to_storefrontcloud:
      name: "Deploy to StorefrontCloud"
      stage: deploy
      node_js: "10"
      script:
        - >
        curl -u $CLOUD_USERNAME:$CLOUD_PASSWORD -H "Content-Type: application/json" -X POST -d "{\"code\":\"mkoszut\", \"frontContainerVersion\":\"$COMMIT\"}" https://farmer.storefrontcloud.io/instances


